config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'enrollments/new'
  root 'courses#index' #what youll see on localhost:3000 page

  resources :users
  resources :courses do
    resources :enrollments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :enrollments, dependent: :destroy
    has_many :users, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :enrollments, dependent: :destroy
    has_many :courses, through: :enrollments

    #user.full_name
    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course
    else
      render :new
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  private
    def set_course 
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_course
  def index
    @teachers = @course.enrollments.where(role: 'teacher')
    @tas = @course.enrollments.where(role: 'ta')
    @students = @course.enrollments.where(role: 'student')
  end

  def new
    @users = User.all - @course.users
    @enrollment = @course.enrollments.new
  end

  def create
    @enrollment = @course.enrollments.new(enrollment_params)

    if @enrollment.save
      redirect_to course_enrollments_path(@course)
    else
      render :new
    end
  end

  def destroy
    enrollment = @course.enrollments.find(params[:id])
    enrollment.destroy
    redirect_to course_enrollments_path(@course)
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:role, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]

  # GET /users
  def index
             #select * from users
    @users = User.all
  end

  # GET /users/:id
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create 
    @user = User.new(user_params)

    if @user.save
      # redirect_to user_path(@user.id)
      # redirect_to user_path(@user)
      redirect_to @user
    else
      render :new
    end
  end

  # DELETE /users/:id
  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/index.html.erb
<h1>Courses</h1>
<%= link_to 'Add Course', new_course_path %>
<hr />
<ul>
    <% @courses.each do |course| %>
    <li>
     <%= link_to course.name, course %>
    </li>
    <% end %>
</ul>

app/views/courses/new.html.erb
<h1>Add Course</h1>
<%= form_for @course do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name, required: true %>
    </div>
<%= f.submit 'If You Dare!'%>
     
    <% end %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
<%= link_to 'Enrollments', course_enrollments_path(@course) %>

app/views/enrollments/index.html.erb
<h1><%= @course.name %>: Enrollments</h1>
<%= link_to 'Add Enrollment', new_course_enrollment_path(@course) %>
<hr />

<h2>Teachers</h2>
<ul>
  <% @teachers.each do |teacher| %>
    <li>
      <%= teacher.user.full_name %>
      <br />
      <%= link_to 'Remove', course_enrollment_path(@course, teacher), method: :delete %>
    </li>
  <% end %>
</ul>
<h2>Tas</h2>
<ul>
  <% @tas.each do |ta| %>
    <li>
      <%= ta.user.full_name %>
      <br />
      <%= link_to 'Remove', course_enrollment_path(@course, ta), method: :delete %>
    </li>
  <% end %>
</ul>
<h2>Students</h2>
<ul>
  <% @students.each do |student| %>
    <li>
      <%= student.user.full_name %>
      <br />
      <%= link_to 'Remove', course_enrollment_path(@course, student), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/enrollments/new.html.erb
<h1>Enroll User</h1>
<%= form_for [@course, @enrollment] do |f| %>
  <%= f.label :user %>
  <%= f.select :user_id, @users.collect { |u| [u.full_name, u.id] } %>
  <br />
  <%= f.label :role %>
  <%= f.select :role, [['Student', 'student'], ['Ta', 'ta'], ['Teacher', 'teacher']] %>
  <br />
  <%= f.submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Courses', courses_path %>
    </li>
    <li>
      <%= link_to 'Add Course', new_course_path %>
    </li>
    <li>
      <%= link_to 'Users', users_path %>
    </li>
    <li>
      <%= link_to 'Add User', new_user_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Canvas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to 'Add User', new_user_path %>
<hr />
<ul>
    <% @users.each do |user| %>
    <li>
     <%= link_to user.full_name, user %>
    </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1> Add User</h1>
<%= form_for @user do |f| %>
    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, required: true %>
    </div>
    <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
</div>
<%= f.submit 'PressMe'%>
     
    <% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<hr />
<h2>Courses</h2>
<ul>
    <% @user.courses.each do |course| %>
        <li>
        <%= link_to course.name, coure %>
        </li>
    <% end %>
    </ul>

    <%= link_to 'Delete User', @user, method: :delete %>